### ISSUE TITLE
Invoking a dialog reloads other components

### ISSUE THREAD

**Issue by ChibiChanNya** [yariksav/vuetify-dialog#42]
Lately I came across a very weird issue when using your dialogs in my Nuxt project. Whenever I invoke a dialog to show up, the page attempts to reload other components, such as vuetify-icons, and it often fails. I'm not sure why this is happening since components are not re-mounted, but it looks like this:
BEFORE:
![image](https://user-images.githubusercontent.com/6617493/60465658-42c68c80-9c17-11e9-8e8a-898026819d47.png)
AFTER:
![image](https://user-images.githubusercontent.com/6617493/60465682-53770280-9c17-11e9-92b2-cace2bf49502.png)

I had originally figured it would be some artifact from developer environment, but it happens in production as well. I have re-installed vuetify-dialog with latest version and using default settings and this continues to happen on any instance of invoking something to show up, for example:

```javascript
 showDialog(){
        this.$dialog.notify.success('TEST!',
          {
            position: 'top-middle',
            timeout: 5000
          })
```

Occasionally the icons return after a moment or two, but sometimes it just stays screwed up like that.
It doesn't affect just icons, as it attempts to reload header scripts like google tag manager, facebook pixel, etc.

**Comment by yariksav** [comment]
Hi! It's srtange. Something happens with icon fonts in vuetify. What kind of vuetify icons do you use? For me is to complicated to understand reason without sufficient information or maybe reproducing example in codesandbox

**Comment by ChibiChanNya** [comment]
Are normal material design icons from Vuetify. For example:
` <v-icon class="blue--text text--lighten-2">phone</v-icon>`
I may have a few fontAwesome ones here and there as well.

I need to make more experiments to be sure what the problem is, it's a kinda big nuxt project so would be hard to replicate on a sandbox but I will see what I can do.

**Comment by yariksav** [comment]
This would be good! You don't need to replicate all project. Just make an little instance in codesandbox. In my projects i haven’t seen this behaivour. But i use just material icons font

**Comment by yariksav** [comment]
And you wrote that showing dialog starts rerendering all page. But it doesn’t have to touch for updating not related components

**Comment by ChibiChanNya** [comment]
Lifecycle hooks don't run again. I tried putting some code on "Mounted" and it doesn't run when this happens. However, the loading bar in Nuxt (default on top of the app) does show for a brief moment even if i'm not navigating anywhere and Facebook pixel tells me I'm attemping to register a duplicate ID every time this happens.

**Comment by ChibiChanNya** [comment]
I've come to the conclusion that the problem module in this case is  "nuxt-i18n" for internationalization. Using your lib is causing it to try to re-render the page. I wonder if I can configure it to avoid this.

**Comment by ChibiChanNya** [comment]
Here is a codesandbox link to try it: https://codesandbox.io/s/github/ChibiChanNya/vuetify-dialog-test/tree/master/?fontsize=14

**Comment by yariksav** [comment]
Thank you, @ChibiChanNya for your work for replication. I've investigated this problem and:
1) After dialog shows - loose all nuxt.head properties in <head> tag
Before
![image](https://user-images.githubusercontent.com/2553313/60502548-b5db0c00-9cc6-11e9-81f7-ddc7718141d8.png)
and after
![image](https://user-images.githubusercontent.com/2553313/60502585-c5f2eb80-9cc6-11e9-80ba-df9d910ba44f.png)
This impacted by nuxt-i18n SEO
To temporary solve this problem you have to add param ```seo: false``` to nuxtI18n option
see https://codesandbox.io/s/vuetify-dialog-test-53ovx
I guess the problem not in vuetify-dialog, because module doesn't inmpact any heads, i18n's and etc

Later I will study code of nuxt-i18n.seo

**Comment by yariksav** [comment]
Please read https://nuxt-community.github.io/nuxt-i18n/seo.html#improving-performance , it's better for perfomance set se to false and then in each layout put code
```
// layouts/default.vue

export default {
  head () {
    return this.$nuxtI18nSeo()
  }
}
```
because this code 
https://github.com/nuxt-community/nuxt-i18n/blob/master/src/templates/seo-head.js
works for EVERY vue component, and dialogs also. And doesn't work correctly each time

Look into lauouts/default.vue at https://codesandbox.io/s/vuetify-dialog-test-53ovx

**Comment by ChibiChanNya** [comment]
Thanks as always @yariksav , second time you save me. I really like this lib. Confirmed all good!
