### ISSUE TITLE
Missing vuetify elmenets on dialog call

### ISSUE THREAD

**Issue by mr337** [yariksav/vuetify-dialog#45]
Hi,

I have imported the vuetify-dialog package but when trying to run a simple notification encountering this error. Using vuecli vuetify scaffold project.

```
[Vue warn]: Unknown custom element: <v-alert> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <DialogChild>
       <Root>
```

**Comment by BasilaryGroup** [comment]
I have the same problem. 

- vuetify: 1.5.16
- vue: 2.6.10
- vuetify-dialog: ~0.4.0-beta.2

I haven't had any problems with Vue + Vuetify. I'm not sure what I have misconfigured.

**Comment by myleslee** [comment]
I'm facing the same problem as well.

vuetify: 2.0.5
vue: 2.6.10 + nuxt.js 2.8.1
vuetify-dialog: @next

Thanks!

**Comment by myleslee** [comment]
I solved the issue by disabling treeshaking feature introduced by `@nuxtjs/vuetify` module. I turned it on for the development environment because the doc used to say it was required in order to get `customVariables` to work. Once I removed it, everything ran smoothly.

A working example can be found here:
https://codesandbox.io/s/vuetify-nuxt-chips-error-gsdcx

**Comment by yariksav** [comment]
@myleslee, can you try version vuetify-dialog@^1.0.0-alpha.2 with enabled treeShake?

**Comment by dmoebius** [comment]
Hi @yariksav,  I can confirm that tree shaking (Vuetify a la carte with vue-cli-plugin-vuetify) works fine together with `vuetify-dialog@1.0.0-alpha.3`. Simply running `npm i vuetify-dialog@next` helped.

However there are still some issues running with Vuetify 2.x which I will report in #46.
