### ISSUE TITLE
$dialog on nuxt plugin V-Snack append outter [data-app=true]

### ISSUE THREAD

**Issue by mean-cj** [yariksav/vuetify-dialog#88]
Hello 

When i use $dialog on Nuxt Plugin 
notify dialog has been append outter [data-app=true]
show color is only black

- "nuxt": "^2.13.2",
- "vuetify": "^2.3.2",
- "vuetify-dialog": "^2.0.6",

**Install  vuetify-dialog on nuxt.config.js**
```
modules: [
 'vuetify-dialog/nuxt'
]

```

Example on nuxt plugin
```
export default ({  $dialog }) => {
     $dialog.message.success('Hello World')
}
```

![2020-07-03_180823](https://user-images.githubusercontent.com/1191385/86463803-62c3eb00-bd58-11ea-8996-e08d6acacbc9.jpg)

**Comment by yariksav** [comment]
Hi, @mean-cj 
Yes, I reproduced this, but all dialogs are show in App instance, after
```
const app = new Vue({
   ...
})
```
As I know when plugins are initializing the app instance in nuxt is not ready yet, i.e snack shows it before [data-app=true] in dom.

And I suppose its not the best way to use dialogs in nuxt plugins, and I will not fix it. You can create PR with yours changes if you want. otherwise you can use it in hooks *created*, etc..

**Comment by mean-cj** [comment]
Hello @yariksav  

Thank your so much.
I don't have any idea for fix this,

now i solve by delay
```
    setTimeout(() => {
        $dialog.message.success('Hello World')
      }, 500)
```
